<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<RootNamespace>Fedestrap.Desktop</RootNamespace>
		<AssemblyName>Fedestrap.Desktop</AssemblyName>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.1.1" />
		<PackageReference Include="Avalonia.Controls.WebView" Version="12.1.0" />
		<PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Fedestrap.Core\Fedestrap.Core.csproj" />
		<ProjectReference Include="..\Fedestrap.Platform.Abstractions\Fedestrap.Platform.Abstractions.csproj" />
	</ItemGroup>
</Project>
