<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<DebugType>embedded</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>True</UseWindowsForms>
		<ApplicationIcon>favicon (1).ico</ApplicationIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<RootNamespace>Fedestrap</RootNamespace>
		<IncludePackageReferencesDuringMarkupCompilation>true</IncludePackageReferencesDuringMarkupCompilation>

		<AssemblyName>Fedestrap</AssemblyName>
		<AssemblyTitle>Fedestrap</AssemblyTitle>
		<Product>Fedestrap</Product>
		<Description>An alternative launcher for Roblox that provides advanced customization, performance tweaks, custom themes, mod management, and rich presence integration.</Description>
		<Company>Fedestrap</Company>
		<Authors>Fedestrap Contributors</Authors>
		<Copyright>Copyright (c) Fedestrap Contributors. Licensed under MIT.</Copyright>
		<PackageProjectUrl>https://github.com/fxderico/Fedestrap</PackageProjectUrl>
		<RepositoryUrl>https://github.com/fxderico/Fedestrap</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<NeutralLanguage>en-US</NeutralLanguage>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<GenerateAssemblyTitleAttribute>true</GenerateAssemblyTitleAttribute>
		<GenerateAssemblyDescriptionAttribute>true</GenerateAssemblyDescriptionAttribute>
		<GenerateAssemblyCompanyAttribute>true</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>true</GenerateAssemblyProductAttribute>
		<GenerateAssemblyCopyrightAttribute>true</GenerateAssemblyCopyrightAttribute>
		

		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>false</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>

		<SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
		<InvariantGlobalization>false</InvariantGlobalization>

		<PublishTrimmed>false</PublishTrimmed>
		<PublishReadyToRun>false</PublishReadyToRun>
		<TieredCompilation>true</TieredCompilation>
		<TieredCompilationQuickJit>true</TieredCompilationQuickJit>
		<TieredCompilationQuickJitForLoops>true</TieredCompilationQuickJitForLoops>
		<TieredPGO>true</TieredPGO>
		<ServerGarbageCollection>false</ServerGarbageCollection>
		<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
		<RetainVMGarbageCollection>false</RetainVMGarbageCollection>

		<DebuggerSupport>false</DebuggerSupport>
		<EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
		<EnableUnsafeUTF7Encoding>false</EnableUnsafeUTF7Encoding>
		<EventSourceSupport>false</EventSourceSupport>
		<HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
		<MetadataUpdaterSupport>false</MetadataUpdaterSupport>
		<UseSystemResourceKeys>false</UseSystemResourceKeys>
		<XmlResolverIsNetworkingEnabledByDefault>false</XmlResolverIsNetworkingEnabledByDefault>

		<OptimizeImplicitlyTriggeredBuild>true</OptimizeImplicitlyTriggeredBuild>
		<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>

		<HighEntropyVA>true</HighEntropyVA>
		<Deterministic>true</Deterministic>
		<DeterministicSourcePaths>false</DeterministicSourcePaths>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest</AnalysisLevel>
		<NoWarn>$(NoWarn);CS8600;CS8601;CS8602;CS8603;CS8604;CS8612;CS8618;CS8619;CS8620;CS8622;CS8625;CS8632;CS8669;CS8670;CS8714;CS0105;CS0108;CS0168;CS0169;CS0219;CS0414;CS0649;CS4014;CS8321;SYSLIB0014;SYSLIB1096;WFDEV004;NU1510;NU1701;MSB3568;MSB3825;PInvoke004;CS8305;CA1416</NoWarn>

		<StartupObject></StartupObject>

		<CsWinRTIncludes>Windows.Foundation;Windows.Graphics.Capture;Windows.Graphics.DirectX;Windows.Graphics.SizeInt32;Windows.Graphics.RectInt32;Windows.Graphics.DisplayId;Windows.UI.WindowId;Windows.Security.Authorization.AppCapabilityAccess.AppCapabilityAccessStatus</CsWinRTIncludes>
		<CsWinRTExcludes>Windows.Foundation.Diagnostics</CsWinRTExcludes>
		<CsWinRTWindowsMetadata>10.0.26100.0</CsWinRTWindowsMetadata>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <WarningLevel>4</WarningLevel>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <WarningLevel>4</WarningLevel>
	</PropertyGroup>
	

	<ItemGroup>
		<None Remove="Resources\mappings.json" />
		<None Remove="Fedestrap.png" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Fedestrap.ico" />
		<Resource Include="Resources\Checkmark.ico" />
		<Resource Include="Resources\CrossMark.ico" />
		<Resource Include="Resources\RobloxFace.png" />
		<Resource Include="Resources\RobloxPlayerIcon.png" />
		<Resource Include="Resources\RobloxStudioIcon.png" />
		<Resource Include="Resources\Fonts\NotoSansThai-VariableFont_wdth,wght.ttf" />
		<Resource Include="Resources\Fonts\Rubik-VariableFont_wght.ttf" />
		<Resource Include="Resources\Fonts\Montserrat-Medium.ttf" />
		<Resource Include="Resources\Fonts\Montserrat-Bold.ttf" />
		<Resource Include="Resources\BootstrapperStyles\ByfronDialog\ByfronLogoDark.jpg" />
		<Resource Include="Resources\BootstrapperStyles\ByfronDialog\ByfronLogoLight.jpg" />
		<Resource Include="Resources\BootstrapperStyles\ByfronDialog\Matt.png" />
		<Resource Include="Resources\MessageBox\Error.png" />
		<Resource Include="Resources\MessageBox\Information.png" />
		<Resource Include="Resources\MessageBox\Question.png" />
		<Resource Include="Resources\MessageBox\Warning.png" />
		<EmbeddedResource Include="Resources\mappings.json" />
		<EmbeddedResource Include="UI\Style\Editor-Theme-Berry.xshd" />
		<EmbeddedResource Include="UI\Style\Editor-Theme-UltraGray.xshd" />
		<EmbeddedResource Include="UI\Style\Editor-Theme-Fedestrap.xshd" />
		<EmbeddedResource Include="UI\Style\Editor-Theme-Blue.xshd" />
		<EmbeddedResource Include="UI\Style\Editor-Theme-Red.xshd" />
        <EmbeddedResource Include="UI\Style\Editor-Theme-Dark.xshd" />
        <EmbeddedResource Include="UI\Style\Editor-Theme-Light.xshd" />
		<EmbeddedResource Include="UI\Style\Editor-Theme-Cyan.xshd" />
		<EmbeddedResource Include="UI\Style\Editor-Theme-Orange.xshd" />
		<EmbeddedResource Include="UI\Style\Editor-Theme-Green.xshd" />
		<EmbeddedResource Include="UI\Style\Editor-Theme-Pink.xshd" />
		<EmbeddedResource Include="UI\Style\Editor-Theme-Purple.xshd" />
		<EmbeddedResource Include="UI\Style\Editor-Theme-Yellow.xshd" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\CustomBootstrapperSchema.json" />
		<EmbeddedResource Include="Resources\CustomBootstrapperTemplate_Blank.xml" />
		<EmbeddedResource Include="Resources\CustomBootstrapperTemplate_Simple.xml" />
		<EmbeddedResource Include="Resources\CustomBootstrapperTemplate_Html.xml" />
		<EmbeddedResource Include="Resources\CustomBootstrapperTemplate_Panel.html" />
		<EmbeddedResource Include="Resources\Mods\Cursor\From2006\ArrowCursor.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\From2006\ArrowFarCursor.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\From2006\ArrowCursorDecalDrag.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\From2013\ArrowCursor.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\From2013\ArrowFarCursor.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\From2013\ArrowCursorDecalDrag.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\FPSCursor\ArrowCursor.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\FPSCursor\ArrowFarCursor.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\FPSCursor\ArrowCursorDecalDrag.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\DotCursor\ArrowCursor.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\DotCursor\ArrowFarCursor.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\DotCursor\ArrowCursorDecalDrag.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\StoofsCursor\ArrowCursor.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\StoofsCursor\ArrowFarCursor.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\StoofsCursor\ArrowCursorDecalDrag.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\CleanCursor\ArrowCursor.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\CleanCursor\ArrowFarCursor.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\CleanCursor\ArrowCursorDecalDrag.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\WhiteDotCursor\ArrowCursor.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\WhiteDotCursor\ArrowFarCursor.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\WhiteDotCursor\ArrowCursorDecalDrag.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\VerySmallWhiteDot\ArrowCursor.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\VerySmallWhiteDot\ArrowFarCursor.png" />
		<EmbeddedResource Include="Resources\Mods\Cursor\VerySmallWhiteDot\ArrowCursorDecalDrag.png" />
		<EmbeddedResource Include="Resources\Mods\Sounds\OldDeath.ogg" />
		<EmbeddedResource Include="Resources\Mods\Sounds\OldGetUp.mp3" />
		<EmbeddedResource Include="Resources\Mods\Sounds\OldJump.mp3" />
		<EmbeddedResource Include="Resources\Mods\Sounds\OldWalk.mp3" />
		<EmbeddedResource Include="Resources\Mods\Sounds\Empty.mp3" />
		<EmbeddedResource Include="Resources\Mods\OldAvatarBackground.rbxl" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AvalonEdit" Version="6.3.1.120" />
		<PackageReference Include="ably.io" Version="1.2.18" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
		<PackageReference Include="Emoji.Wpf" Version="0.3.4" />
		<PackageReference Include="Markdig" Version="1.3.2" />
		<PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.29.0" />
		<PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.2.5" ExcludeAssets="native;build;buildTransitive" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
		<PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.3.1" />
		<!-- <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" /> -->

		<PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.321">
			<!--<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>-->
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="NAudio" Version="3.0.1" />
		<PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Nefarius.ViGEm.Client" Version="1.21.256" />
		<PackageReference Include="NVorbis" Version="0.10.5" />
		<PackageReference Include="OggVorbisEncoder" Version="1.2.2" />
		<PackageReference Include="securifybv.ShellLink" Version="0.1.0" />
		<PackageReference Include="SharpZipLib" Version="1.4.2" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
		<PackageReference Include="System.Management" Version="10.0.11" />

		<PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.11" />

		<PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />

		<PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />

		<PackageReference Include="Vortice.DirectComposition" Version="3.8.3" />

		<PackageReference Include="Vortice.DXGI" Version="3.8.3" />
		<PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
		<PackageReference Include="XamlAnimatedGif" Version="2.3.2" />
		<PackageReference Include="Openize.Drako" Version="26.2.0" />
		<PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
		<!-- <PackageReference Include="YoutubeExplode" Version="6.5.5" />
		<PackageReference Include="YoutubeExplode.Converter" Version="6.5.5" /> -->
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Fedestrap.Core\Fedestrap.Core.csproj" />
		<ProjectReference Include="..\Fedestrap.Platform.Abstractions\Fedestrap.Platform.Abstractions.csproj" />
		<ProjectReference Include="..\Fedestrap.Platform.Linux\Fedestrap.Platform.Linux.csproj" />
		<ProjectReference Include="..\Fedestrap.Platform.MacOS\Fedestrap.Platform.MacOS.csproj" />
		<ProjectReference Include="..\..\external\wpfui\src\Wpf.Ui\Wpf.Ui.csproj" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="Fedestrap.Models.Attributes.BuildMetadataAttribute">
			<_Parameter1>1970-01-01T00:00:00Z</_Parameter1>
			<_Parameter2></_Parameter2>
			<_Parameter3>$(CommitHash)</_Parameter3>
			<_Parameter4>$(CommitRef)</_Parameter4>
		</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="NativeMethods.txt" />

		<!-- Provide the path to the winmds used as input into the analyzer. -->
		<CompilerVisibleProperty Include="CsWin32InputMetadataPaths" />
		<CompilerVisibleProperty Include="CsWin32InputDocPaths" />
	</ItemGroup>

	<Target Name="AssembleCsWin32InputPaths" BeforeTargets="GenerateMSBuildEditorConfigFileCore">
		<!-- Roslyn only allows source generators to see msbuild properties, to lift msbuild items into semicolon-delimited properties. -->
		<PropertyGroup>
			<CsWin32InputMetadataPaths>@(ProjectionMetadataWinmd->'%(FullPath)','|')</CsWin32InputMetadataPaths>
			<CsWin32InputDocPaths>@(ProjectionDocs->'%(FullPath)','|')</CsWin32InputDocPaths>
		</PropertyGroup>
	</Target>

	<Target Name="FixMds" BeforeTargets="CoreCompile" Condition="'@(ProjectionMetadataWinmd)'==''">
		<ItemGroup>
			<ProjectionMetadataWinmd Include="$(UserProfile)\.nuget\packages\microsoft.windows.sdk.win32metadata\69.0.7-preview\Windows.Win32.winmd" />
		</ItemGroup>
	</Target>

	<ItemGroup>
	  <None Include="ThirdParty\NvOFFRUC.dll" CopyToOutputDirectory="PreserveNewest" Link="NvOFFRUC.dll" />
	  <None Include="ThirdParty\cudart64_110.dll" CopyToOutputDirectory="PreserveNewest" Link="cudart64_110.dll" />
	</ItemGroup>


	<ItemGroup>
	  <Resource Include="Fedestrap.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </Resource>
	</ItemGroup>


	<ItemGroup>
	  <None Include="..\..\LICENSE.FEDESTRAP">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Include="Utility\DarkTexturesMod.cs" />
	</ItemGroup>



	<ItemGroup>
		<Compile Update="Properties\Settings.Designer.cs">
			<DesignTimeSharedInput>True</DesignTimeSharedInput>
			<AutoGen>True</AutoGen>
			<DependentUpon>Settings.settings</DependentUpon>
		</Compile>
		<Compile Update="Resources\Strings.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Strings.resx</DependentUpon>
		</Compile>
		<EmbeddedResource Update="Resources\Strings.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Strings.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<None Update="Properties\Settings.settings">
			<Generator>SettingsSingleFileGenerator</Generator>
			<LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>
	</ItemGroup>

	<Target Name="StripDocsFromPublish" AfterTargets="ComputeResolvedFilesToPublishList">
		<ItemGroup>
			<ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(ResolvedFileToPublish.Extension)' == '.xml' Or '%(ResolvedFileToPublish.Extension)' == '.pdb' Or '%(ResolvedFileToPublish.Extension)' == '.txt'" />
			<ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(ResolvedFileToPublish.RelativePath)' == 'runtimes\win-x64\native\WebView2Loader.dll'" />
		</ItemGroup>
	</Target>

</Project>
